### ISSUE TITLE
Two comparisons for approximate visualizations

### ISSUE THREAD

**Issue by depstein** [domoritz/bias-study#15]
There are still two comparisons for approximate visualizations.
`addBasicQuestions('.form', presentationOrder[whichOne], 2);`
This is an easy fix, but verifying this wasn't intended behavior.

**Comment by domoritz** [comment]
Yeah, I wasn't sure whether we want to keep it. It's going to give us more reliable data about the baseline error. Let's keep it. 

If we see that the overall time is significantly less than 10 minutes, we could even ask 3 questions for the precise visualizations to get more data.

**Comment by domoritz** [comment]
Here are the timings in minutes. 
![image](https://cloud.githubusercontent.com/assets/589034/20816447/288542c0-b7d7-11e6-9fc8-df3f5d61cb36.png)

I feel we can definitely ask 3 precise questions! The long times are because participants spent a lot of time on some pages (doing something else?)

**Comment by depstein** [comment]
I've been staring at the time data too... A two participants spent multiple minutes on each of the approximate visualizations.

I think this is fine, but wanted to mention. I agree that 3 precise questions is fine.
