### ISSUE TITLE
Occasional missing data

### ISSUE THREAD

**Issue by depstein** [domoritz/bias-study#16]
We're occasionally missing answers to questions and timing data for pages. The data we're missing seems to be correlated (e.g., if we didn't get an answer, we probably also didn't get the timing data).

This makes me wonder whether it's an issue uploading to the database? But I'm really not sure.

**Comment by domoritz** [comment]
Very odd, I suspect the issue is that firebase does asynchronously sync with the backend and we may be missing data due to that. But it could well be something else. We definitely have data missing in 4/10 participants. This should be fixed.

**Comment by domoritz** [comment]
Okay, if firebase was the issue, it should be fixed. I now only proceed to the next page if everything is synced.

**Comment by domoritz** [comment]
Still missing some data but we ran the study so ¯\_(ツ)_/¯
