### ISSUE TITLE
Pilot findings

### ISSUE THREAD

**Issue by domoritz** [domoritz/bias-study#3]
- [x] create distance visualizations, M
- [x] show difference visualization, E
- [x] change text to tell people to do things based on viz, E
- [x] checkbox to indicate that you read the viz, E
- [x] Add questions after seeing the approximate visualization, E
- [x] make sure we only ask questions about data that was actually in the charts, M
- [x] change text to say "I don't remember" and "I'm certain", E
- [x] Do you notice a difference? question on precise vis, E
- [x] Orange for approximate, blue for precise, M
- [x] Sliders should be below questions, not next to them, E
- [x] Prevent back button, M

**Comment by domoritz** [comment]
I generated new charts and also added plots that show the difference.

**Comment by depstein** [comment]
I migrated to the new sets of visualizations, added the difference visualizations, and moved the questions. But this meant scrapping pretty much all the questions... going to work on cleaning those up in a way that's a little more reproducible (meaning, not hard-coding every question)

**Comment by depstein** [comment]
Ok, I think I'm done with my part.

**Comment by domoritz** [comment]
I changed the code to use `window.location.replace('foo.html')` so that yu cannot go back. Unfortunately, that meant that the forms don't work correctly right now but I think @depstein will change the way we submit forms anyway when we have different questions for the first and the second viz.
