### ISSUE TITLE
Sometimes the "next" button doesn't work

### ISSUE THREAD

**Issue by domoritz** [domoritz/bias-study#4]

**Comment by depstein** [comment]
Can you give me any more info, or repro steps?

**Comment by domoritz** [comment]
I just tried to go through the study but at some point couldn't click the "Continue" button anymore on https://www.domoritz.de/bias-study/precise.html?. I can't reliably reproduce it.

**Comment by depstein** [comment]
Okay, I'll give it a look over the weekend... hope it's not blocking you.

**Comment by domoritz** [comment]
No it's not blocking. I just wanted to make sure that we thoroughly test before we deploy.

**Comment by domoritz** [comment]
This should be fixed with all the refactorings.
