### ISSUE TITLE
Recommended minor fixes from pilot

### ISSUE THREAD

**Issue by depstein** [domoritz/bias-study#7]
- [x] The approximate and precise visualizations should be labeled in the side-by-side condition.
- [x] The instructions should make clear that the questions will appear after _both_ precise visualizations.
- [x] The default certainty rating of 50 is too tempting for participants, and is leading to an anchoring effect. The default should either be changed to 0 or 100, or (my vote) be changed to a 7-item likert with no default rating.

**Comment by depstein** [comment]
@domoritz can you weigh in on point 3?

**Comment by domoritz** [comment]
I like the 7 item likert scale without a default. It's too tempting to just leave the rating as it was.
